DROP TABLE IF EXISTS wiki_governance_metric_events;
DROP TABLE IF EXISTS wiki_reviews;
DROP TABLE IF EXISTS wiki_change_items;
DROP TABLE IF EXISTS wiki_change_sets;
DROP TABLE IF EXISTS wiki_package_pages;
DROP TABLE IF EXISTS wiki_packages;
DROP TABLE IF EXISTS wiki_scenarios;
DROP INDEX IF EXISTS idx_wiki_pages_business_line;
DROP INDEX IF EXISTS idx_wiki_pages_card_filter;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS effective_to;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS effective_from;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS reviewed_at;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS reviewed_by;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS prohibited_claims;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS applicability;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS affected_metrics;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS audience_roles;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS scenario_ids;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS business_line;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS review_status;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS answer_strength;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS maturity_status;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS knowledge_type;
