package main

const adminHTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>WeKnora MCP 管理后台</title>
<style>
:root{font-family:Inter,"PingFang SC","Microsoft YaHei",sans-serif;color:#18202c;background:#f3f6f9}*{box-sizing:border-box}body{margin:0}button,input,select{font:inherit}.hidden{display:none!important}
.login{min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at 20% 10%,#d7fff0,transparent 35%),#eef3f6}.login-card{width:min(430px,90vw);background:#fff;padding:36px;border-radius:18px;box-shadow:0 24px 70px #2342}.brand{display:flex;gap:12px;align-items:center}.logo{width:42px;height:42px;border-radius:12px;background:#16b777;color:white;display:grid;place-items:center;font-weight:800}.login h1{margin:22px 0 8px}.muted{color:#718096;font-size:14px}.field{display:flex;flex-direction:column;gap:7px;margin:20px 0}.field input,.toolbar input,.toolbar select{border:1px solid #d8e0e8;border-radius:9px;padding:10px 12px;background:white}.btn{border:0;border-radius:9px;padding:10px 15px;cursor:pointer}.primary{background:#16b777;color:white}.secondary{background:#edf2f5;color:#334155}.danger{background:#fff0f0;color:#d33}.login .btn{width:100%}.error{color:#d33;font-size:13px;margin-top:10px}
.app{min-height:100vh;display:grid;grid-template-columns:230px 1fr}.sidebar{background:#101b24;color:#c9d4dc;padding:24px 16px}.side-brand{font-weight:750;font-size:18px;color:white;padding:0 10px 28px}.nav{display:flex;flex-direction:column;gap:6px}.nav button{border:0;background:transparent;color:#aebac4;text-align:left;padding:11px 13px;border-radius:9px;cursor:pointer}.nav button.active{background:#16b777;color:white}.side-foot{position:fixed;bottom:22px;width:198px}.main{padding:30px;overflow:auto}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.head h1{margin:0;font-size:25px}.cards{display:grid;grid-template-columns:repeat(6,1fr);gap:14px;margin-bottom:24px}.card,.panel{background:white;border:1px solid #e3e9ee;border-radius:13px}.stat{padding:19px}.stat span{color:#718096;font-size:13px}.stat strong{display:block;font-size:28px;margin-top:7px}.panel{overflow:hidden}.panel-head{display:flex;align-items:center;justify-content:space-between;padding:17px 19px;border-bottom:1px solid #edf1f4}.panel-head h2{font-size:16px;margin:0}.toolbar{display:flex;gap:9px;flex-wrap:wrap}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:13px 17px;border-bottom:1px solid #edf1f4;font-size:13px;white-space:nowrap}th{color:#718096;background:#fafcfd}.badge{padding:4px 8px;border-radius:20px;background:#edf2f5}.ok{background:#e8faf2;color:#11855a}.bad{background:#fff0f0;color:#cc3535}.warn{background:#fff7df;color:#9a6700}.actions{display:flex;gap:6px}.actions .btn{padding:6px 9px;font-size:12px}.empty{text-align:center;color:#8a98a5;padding:45px}.modal-bg{position:fixed;inset:0;background:#1228;display:grid;place-items:center;padding:20px}.modal{width:min(560px,92vw);max-height:88vh;overflow:auto;background:white;border-radius:14px;padding:24px}.modal.wide{width:min(900px,94vw)}.modal h3{margin-top:0}.check-row{display:flex;gap:20px;margin:16px 0}.token-box,.code-box{word-break:break-all;background:#0f1b24;color:#bfffe3;border-radius:9px;padding:14px;font-family:monospace;white-space:pre-wrap}.detail-grid{display:grid;grid-template-columns:140px 1fr;gap:10px 16px;font-size:14px}.detail-grid b{color:#64748b}.detail-grid div{white-space:pre-wrap;word-break:break-word}.reference{border:1px solid #e4e9ee;border-radius:10px;padding:13px;margin-top:10px}.reference p{white-space:pre-wrap;word-break:break-word}.toast{position:fixed;right:24px;bottom:24px;background:#101b24;color:white;padding:12px 17px;border-radius:9px;box-shadow:0 10px 35px #0004}
@media(max-width:1100px){.cards{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.app{grid-template-columns:1fr}.sidebar{position:static}.side-foot{position:static;margin-top:20px;width:auto}.nav{flex-direction:row;flex-wrap:wrap}.main{padding:18px}.cards{grid-template-columns:repeat(2,1fr)}}
</style></head><body>
<section id="login" class="login"><div class="login-card"><div class="brand"><div class="logo">M</div><b>WeKnora MCP</b></div><h1>管理后台</h1><p class="muted">管理访问成员、读写权限、反馈溯源和 MCP 调用审计。</p><div class="field"><label>管理密钥</label><input id="adminToken" type="password" placeholder="输入 WEKNORA_MCP_ADMIN_TOKEN"></div><button class="btn primary" onclick="login()">进入后台</button><div id="loginError" class="error"></div></div></section>
<section id="app" class="app hidden"><aside class="sidebar"><div class="side-brand">WeKnora MCP</div><nav class="nav"><button id="navDashboard" class="active" onclick="showPage('dashboard')">仪表盘</button><button id="navMembers" onclick="showPage('members')">成员与权限</button><button id="navFeedback" onclick="showPage('feedback')">知识反馈</button><button id="navLogs" onclick="showPage('logs')">调用日志</button></nav><div class="side-foot"><button class="btn secondary" onclick="logout()">退出管理</button></div></aside><main class="main">
<div class="head"><div><h1 id="pageTitle">MCP 管理概览</h1><div class="muted">独立于 WeKnora 前台的 MCP 运维、反馈与权限中心</div></div><button class="btn secondary" onclick="refreshCurrent()">刷新</button></div>
<section id="dashboardPage"><div class="cards"><div class="card stat"><span>成员总数</span><strong id="membersCount">-</strong></div><div class="card stat"><span>启用成员</span><strong id="enabledCount">-</strong></div><div class="card stat"><span>总调用</span><strong id="callsCount">-</strong></div><div class="card stat"><span>失败调用</span><strong id="failedCount">-</strong></div><div class="card stat"><span>知识反馈</span><strong id="feedbackCount">-</strong></div><div class="card stat"><span>溯源异常</span><strong id="mismatchCount">-</strong></div></div><div class="panel"><div class="panel-head"><h2>最近调用</h2></div><div id="recentLogs"></div></div></section>
<section id="membersPage" class="hidden"><div class="panel"><div class="panel-head"><h2>成员列表</h2><button class="btn primary" onclick="openMemberModal()">新增成员</button></div><div id="membersTable"></div></div></section>
<section id="feedbackPage" class="hidden"><div class="panel"><div class="panel-head"><h2>用户知识反馈</h2><div class="toolbar"><select id="feedbackTypeFilter" onchange="loadFeedback()"><option value="">全部类型</option><option value="incorrect">错误</option><option value="outdated">过时</option><option value="incomplete">不完整</option><option value="irrelevant">不相关</option><option value="wrong_reference">引用错误</option><option value="missing_knowledge">知识缺失</option><option value="suggestion">建议</option><option value="other">其他</option></select><select id="traceFilter" onchange="loadFeedback()"><option value="">全部溯源状态</option><option value="verified">已验证</option><option value="untraced">未关联</option><option value="trace_mismatch">溯源异常</option></select></div></div><div id="feedbackTable"></div></div></section>
<section id="logsPage" class="hidden"><div class="panel"><div class="panel-head"><h2>调用日志</h2><div class="toolbar"><input id="toolFilter" placeholder="工具名" oninput="loadLogs()"><select id="statusFilter" onchange="loadLogs()"><option value="">全部状态</option><option value="success">success</option><option value="failed">failed</option><option value="denied">denied</option></select></div></div><div id="logsTable"></div></div></section>
</main></section>
<div id="memberModal" class="modal-bg hidden"><div class="modal"><h3>新增 MCP 成员</h3><div class="field"><label>成员名称</label><input id="memberName" placeholder="例如：客服 Agent"></div><div class="check-row"><label><input id="canRead" type="checkbox" checked> 允许问答和反馈</label><label><input id="canWrite" type="checkbox"> 允许知识写入</label></div><div class="actions"><button class="btn primary" onclick="createMember()">创建</button><button class="btn secondary" onclick="closeMemberModal()">取消</button></div></div></div>
<div id="tokenModal" class="modal-bg hidden"><div class="modal"><h3>一次性成员令牌</h3><p class="muted">令牌只显示一次，请立即保存。</p><div id="newToken" class="token-box"></div><div class="actions" style="margin-top:16px"><button class="btn primary" onclick="copyToken()">复制</button><button class="btn secondary" onclick="closeTokenModal()">关闭</button></div></div></div>
<div id="feedbackModal" class="modal-bg hidden"><div class="modal wide"><div class="panel-head" style="padding:0 0 16px"><h3 style="margin:0">反馈详情与召回快照</h3><button class="btn secondary" onclick="closeFeedbackModal()">关闭</button></div><div id="feedbackDetail" style="margin-top:18px"></div></div></div>
<div id="toast" class="toast hidden"></div>
<script>
const $=id=>document.getElementById(id);let adminToken=localStorage.getItem('weknoraMCPAdminToken')||'';let currentPage='dashboard';
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch('/admin/api'+path,{...options,headers:{'Authorization':'Bearer '+adminToken,'Content-Type':'application/json',...(options.headers||{})}});const j=await r.json().catch(()=>({error:'请求失败'}));if(!r.ok)throw new Error(j.error||'请求失败');return j}
async function login(){adminToken=$('adminToken').value.trim();try{await api('/overview');localStorage.setItem('weknoraMCPAdminToken',adminToken);$('login').classList.add('hidden');$('app').classList.remove('hidden');showPage('dashboard')}catch(e){$('loginError').textContent=e.message}}
function logout(){localStorage.removeItem('weknoraMCPAdminToken');adminToken='';$('app').classList.add('hidden');$('login').classList.remove('hidden')}
function showPage(page){currentPage=page;['dashboard','members','feedback','logs'].forEach(p=>{$(p+'Page').classList.toggle('hidden',p!==page);$('nav'+p[0].toUpperCase()+p.slice(1)).classList.toggle('active',p===page)});$('pageTitle').textContent={dashboard:'MCP 管理概览',members:'成员与权限',feedback:'知识反馈与溯源',logs:'调用日志'}[page];refreshCurrent()}
function refreshCurrent(){if(currentPage==='dashboard')loadDashboard();if(currentPage==='members')loadMembers();if(currentPage==='feedback')loadFeedback();if(currentPage==='logs')loadLogs()}
async function loadDashboard(){try{const o=(await api('/overview')).data;$('membersCount').textContent=o.members;$('enabledCount').textContent=o.enabled_members;$('callsCount').textContent=o.calls;$('failedCount').textContent=o.failed_calls;$('feedbackCount').textContent=o.feedback;$('mismatchCount').textContent=o.trace_mismatches;renderLogs((await api('/logs?page=1&page_size=8')).data,$('recentLogs'))}catch(e){toast(e.message)}}
async function loadMembers(){try{renderMembers((await api('/members')).data)}catch(e){toast(e.message)}}
function renderMembers(rows){if(!rows.length){$('membersTable').innerHTML='<div class="empty">暂无成员</div>';return}$('membersTable').innerHTML='<div class="table-wrap"><table><thead><tr><th>成员</th><th>令牌</th><th>问答/反馈</th><th>知识写入</th><th>状态</th><th>最近使用</th><th>操作</th></tr></thead><tbody>'+rows.map(m=>'<tr><td><b>'+esc(m.name)+'</b></td><td><code>'+esc(m.token_prefix)+'</code></td><td>'+perm(m.can_read)+'</td><td>'+perm(m.can_write)+'</td><td><span class="badge '+(m.enabled?'ok':'bad')+'">'+(m.enabled?'启用':'已禁用')+'</span></td><td>'+fmt(m.last_used_at)+'</td><td class="actions"><button class="btn secondary" onclick="toggleMember('+m.id+',\'can_read\','+!m.can_read+')">'+(m.can_read?'关闭问答':'开启问答')+'</button><button class="btn secondary" onclick="toggleMember('+m.id+',\'can_write\','+!m.can_write+')">'+(m.can_write?'关闭写入':'开启写入')+'</button><button class="btn '+(m.enabled?'danger':'primary')+'" onclick="toggleMember('+m.id+',\'enabled\','+!m.enabled+')">'+(m.enabled?'禁用':'启用')+'</button><button class="btn secondary" onclick="rotateToken('+m.id+')">换令牌</button></td></tr>').join('')+'</tbody></table></div>'}
const perm=v=>'<span class="badge '+(v?'ok':'')+'">'+(v?'允许':'禁止')+'</span>';async function toggleMember(id,key,value){try{await api('/members/'+id,{method:'PATCH',body:JSON.stringify({[key]:value})});loadMembers()}catch(e){toast(e.message)}}
function openMemberModal(){$('memberName').value='';$('canRead').checked=true;$('canWrite').checked=false;$('memberModal').classList.remove('hidden')}function closeMemberModal(){$('memberModal').classList.add('hidden')}
async function createMember(){try{const r=await api('/members',{method:'POST',body:JSON.stringify({name:$('memberName').value,can_read:$('canRead').checked,can_write:$('canWrite').checked})});closeMemberModal();showToken(r.token);loadMembers()}catch(e){toast(e.message)}}
async function rotateToken(id){if(!confirm('更换后旧令牌会立即失效，确定继续吗？'))return;try{const r=await api('/members/'+id+'/rotate-token',{method:'POST'});showToken(r.token);loadMembers()}catch(e){toast(e.message)}}
function showToken(v){$('newToken').textContent=v;$('tokenModal').classList.remove('hidden')}function closeTokenModal(){$('tokenModal').classList.add('hidden')}async function copyToken(){await navigator.clipboard.writeText($('newToken').textContent);toast('令牌已复制')}
async function loadFeedback(){try{const q=new URLSearchParams({page:'1',page_size:'100'});if($('feedbackTypeFilter').value)q.set('feedback_type',$('feedbackTypeFilter').value);if($('traceFilter').value)q.set('trace_status',$('traceFilter').value);renderFeedback((await api('/feedback?'+q)).data)}catch(e){toast(e.message)}}
function traceBadge(v){return '<span class="badge '+(v==='verified'?'ok':v==='trace_mismatch'?'bad':'warn')+'">'+esc(v)+'</span>'}
function renderFeedback(rows){if(!rows.length){$('feedbackTable').innerHTML='<div class="empty">暂无反馈</div>';return}$('feedbackTable').innerHTML='<div class="table-wrap"><table><thead><tr><th>时间</th><th>成员</th><th>类型</th><th>反馈</th><th>知识库</th><th>溯源</th><th>召回/目标节点</th><th>操作</th></tr></thead><tbody>'+rows.map(f=>'<tr><td>'+fmt(f.created_at)+'</td><td>'+esc(f.member_name||'stdio/未知')+'</td><td><code>'+esc(f.feedback_type)+'</code></td><td style="max-width:360px;overflow:hidden;text-overflow:ellipsis">'+esc(f.feedback_text)+'</td><td><code>'+esc(f.knowledge_base_id||'-')+'</code></td><td>'+traceBadge(f.trace_status)+'</td><td>'+(f.recalled_node_ids||[]).length+' / '+(f.target_node_ids||[]).length+'</td><td><button class="btn secondary" onclick="showFeedback(\''+esc(f.id)+'\')">查看溯源</button></td></tr>').join('')+'</tbody></table></div>'}
async function showFeedback(id){try{const f=(await api('/feedback/'+encodeURIComponent(id))).data;let html='<div class="detail-grid"><b>反馈 ID</b><div><code>'+esc(f.id)+'</code></div><b>成员</b><div>'+esc(f.member_name||'stdio/未知')+'</div><b>类型</b><div>'+esc(f.feedback_type)+'</div><b>反馈内容</b><div>'+esc(f.feedback_text)+'</div><b>原问题</b><div>'+esc(f.original_question||'-')+'</div><b>回答摘录</b><div>'+esc(f.answer_excerpt||'-')+'</div><b>建议修正</b><div>'+esc(f.suggested_correction||'-')+'</div><b>Request ID</b><div><code>'+esc(f.related_request_id||'-')+'</code></div><b>溯源状态</b><div>'+traceBadge(f.trace_status)+' '+esc(f.trace_message||'')+'</div><b>召回节点</b><div><code>'+esc((f.recalled_node_ids||[]).join(', ')||'-')+'</code></div><b>目标节点</b><div><code>'+esc((f.target_node_ids||[]).join(', ')||'-')+'</code></div></div><h3 style="margin-top:24px">保存的召回快照</h3>';if(!(f.references||[]).length)html+='<div class="empty">没有可验证的召回快照</div>';else html+=(f.references||[]).map(r=>'<div class="reference"><div><b>#'+r.rank+' '+esc(r.knowledge_title||'未命名知识')+'</b> · score '+r.score+'</div><div class="muted"><code>'+esc(r.node_id)+'</code> · '+esc(r.match_type||'-')+' · '+esc(r.content_hash||'-')+'</div><p>'+esc(r.content_excerpt||'-')+'</p></div>').join('');$('feedbackDetail').innerHTML=html;$('feedbackModal').classList.remove('hidden')}catch(e){toast(e.message)}}function closeFeedbackModal(){$('feedbackModal').classList.add('hidden')}
async function loadLogs(){try{const q=new URLSearchParams({page:'1',page_size:'100'});if($('toolFilter').value)q.set('tool',$('toolFilter').value);if($('statusFilter').value)q.set('status',$('statusFilter').value);renderLogs((await api('/logs?'+q)).data,$('logsTable'))}catch(e){toast(e.message)}}
function renderLogs(rows,target){if(!rows.length){target.innerHTML='<div class="empty">暂无调用日志</div>';return}target.innerHTML='<div class="table-wrap"><table><thead><tr><th>时间</th><th>成员</th><th>工具</th><th>请求内容</th><th>知识库</th><th>状态</th><th>耗时</th><th>Request ID</th></tr></thead><tbody>'+rows.map(l=>'<tr title="'+esc(l.error_message)+'"><td>'+fmt(l.created_at)+'</td><td>'+esc(l.member_name||'未知')+'</td><td><code>'+esc(l.tool)+'</code></td><td style="max-width:330px;overflow:hidden;text-overflow:ellipsis">'+esc(l.subject||'-')+'</td><td><code>'+esc(l.knowledge_base_id||'-')+'</code></td><td><span class="badge '+(l.status==='success'?'ok':'bad')+'">'+esc(l.status)+'</span></td><td>'+l.duration_ms+' ms</td><td><code>'+esc(l.request_id||'-')+'</code></td></tr>').join('')+'</tbody></table></div>'}
function fmt(v){return v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'-'}function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2500)}
if(adminToken){$('login').classList.add('hidden');$('app').classList.remove('hidden');showPage('dashboard')}
</script></body></html>`
