package main

const adminHTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>WeKnora MCP 管理后台</title>
<style>
:root{font-family:Inter,"PingFang SC","Microsoft YaHei",sans-serif;color:#18202c;background:#f3f6f9}*{box-sizing:border-box}body{margin:0}button,input,select{font:inherit}.hidden{display:none!important}
.login{min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at 20% 10%,#d7fff0,transparent 35%),#eef3f6}.login-card{width:min(430px,90vw);background:#fff;padding:36px;border-radius:18px;box-shadow:0 24px 70px #2342  }.brand{display:flex;gap:12px;align-items:center}.logo{width:42px;height:42px;border-radius:12px;background:#16b777;color:white;display:grid;place-items:center;font-weight:800}.login h1{margin:22px 0 8px}.muted{color:#718096;font-size:14px}.field{display:flex;flex-direction:column;gap:7px;margin:20px 0}.field input,.toolbar input,.toolbar select{border:1px solid #d8e0e8;border-radius:9px;padding:10px 12px;background:white}.btn{border:0;border-radius:9px;padding:10px 15px;cursor:pointer}.primary{background:#16b777;color:white}.secondary{background:#edf2f5;color:#334155}.danger{background:#fff0f0;color:#d33}.login .btn{width:100%}.error{color:#d33;font-size:13px;margin-top:10px}
.app{min-height:100vh;display:grid;grid-template-columns:230px 1fr}.sidebar{background:#101b24;color:#c9d4dc;padding:24px 16px}.side-brand{font-weight:750;font-size:18px;color:white;padding:0 10px 28px}.nav{display:flex;flex-direction:column;gap:6px}.nav button{border:0;background:transparent;color:#aebac4;text-align:left;padding:11px 13px;border-radius:9px;cursor:pointer}.nav button.active{background:#16b777;color:white}.side-foot{position:fixed;bottom:22px;width:198px}.main{padding:30px;overflow:auto}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.head h1{margin:0;font-size:25px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:24px}.card,.panel{background:white;border:1px solid #e3e9ee;border-radius:13px}.stat{padding:19px}.stat span{color:#718096;font-size:13px}.stat strong{display:block;font-size:28px;margin-top:7px}.panel{overflow:hidden}.panel-head{display:flex;align-items:center;justify-content:space-between;padding:17px 19px;border-bottom:1px solid #edf1f4}.panel-head h2{font-size:16px;margin:0}.toolbar{display:flex;gap:9px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:13px 17px;border-bottom:1px solid #edf1f4;font-size:13px;white-space:nowrap}th{color:#718096;background:#fafcfd}.badge{padding:4px 8px;border-radius:20px;background:#edf2f5}.ok{background:#e8faf2;color:#11855a}.bad{background:#fff0f0;color:#cc3535}.actions{display:flex;gap:6px}.actions .btn{padding:6px 9px;font-size:12px}.empty{text-align:center;color:#8a98a5;padding:45px}.modal-bg{position:fixed;inset:0;background:#1228;display:grid;place-items:center}.modal{width:min(480px,92vw);background:white;border-radius:14px;padding:24px}.modal h3{margin-top:0}.check-row{display:flex;gap:20px;margin:16px 0}.token-box{word-break:break-all;background:#0f1b24;color:#bfffe3;border-radius:9px;padding:14px;font-family:monospace}.toast{position:fixed;right:24px;bottom:24px;background:#101b24;color:white;padding:12px 17px;border-radius:9px;box-shadow:0 10px 35px #0004}
@media(max-width:900px){.app{grid-template-columns:1fr}.sidebar{position:static}.side-foot{position:static;margin-top:20px;width:auto}.nav{flex-direction:row}.main{padding:18px}.cards{grid-template-columns:repeat(2,1fr)}}
</style></head><body>
<section id="login" class="login"><div class="login-card"><div class="brand"><div class="logo">M</div><b>WeKnora MCP</b></div><h1>管理后台</h1><p class="muted">管理访问成员、读写权限和 MCP 调用审计日志。</p><div class="field"><label>管理密钥</label><input id="adminToken" type="password" placeholder="输入 WEKNORA_MCP_ADMIN_TOKEN"></div><button class="btn primary" onclick="login()">进入后台</button><div id="loginError" class="error"></div></div></section>
<section id="app" class="app hidden"><aside class="sidebar"><div class="side-brand">WeKnora MCP</div><nav class="nav"><button id="navDashboard" class="active" onclick="showPage('dashboard')">仪表盘</button><button id="navMembers" onclick="showPage('members')">成员与权限</button><button id="navLogs" onclick="showPage('logs')">调用日志</button></nav><div class="side-foot"><button class="btn secondary" onclick="logout()">退出管理</button></div></aside><main class="main">
<div class="head"><div><h1 id="pageTitle">MCP 管理概览</h1><div class="muted">独立于 WeKnora 前台的 MCP 运维与权限中心</div></div><button class="btn secondary" onclick="refreshCurrent()">刷新</button></div>
<section id="dashboardPage"><div class="cards"><div class="card stat"><span>成员总数</span><strong id="membersCount">-</strong></div><div class="card stat"><span>启用成员</span><strong id="enabledCount">-</strong></div><div class="card stat"><span>调用总数</span><strong id="callsCount">-</strong></div><div class="card stat"><span>失败调用</span><strong id="failedCount">-</strong></div></div><div class="panel"><div class="panel-head"><h2>最近调用</h2><button class="btn secondary" onclick="showPage('logs')">查看全部</button></div><div id="recentLogs"></div></div></section>
<section id="membersPage" class="hidden"><div class="panel"><div class="panel-head"><h2>访问成员</h2><button class="btn primary" onclick="openMemberModal()">新增成员</button></div><div id="membersTable"></div></div></section>
<section id="logsPage" class="hidden"><div class="panel"><div class="panel-head"><h2>调用审计日志</h2><div class="toolbar"><select id="toolFilter" onchange="loadLogs()"><option value="">全部工具</option><option>ask_wiki</option><option>ask_rag</option><option>update_knowledge</option><option>upload_knowledge_file</option><option value="authentication">鉴权</option></select><select id="statusFilter" onchange="loadLogs()"><option value="">全部状态</option><option value="success">成功</option><option value="failed">失败</option><option value="denied">拒绝</option></select></div></div><div id="logsTable"></div></div></section>
</main></section>
<div id="memberModal" class="modal-bg hidden"><div class="modal"><h3>新增访问成员</h3><div class="field"><label>成员名称</label><input id="memberName" placeholder="例如：产品部小王 / 测试设备 A"></div><div class="check-row"><label><input id="canRead" type="checkbox" checked> 允许问答</label><label><input id="canWrite" type="checkbox"> 允许更新知识库</label></div><div style="display:flex;justify-content:flex-end;gap:8px"><button class="btn secondary" onclick="closeMemberModal()">取消</button><button class="btn primary" onclick="createMember()">创建并生成令牌</button></div></div></div>
<div id="tokenModal" class="modal-bg hidden"><div class="modal"><h3>成员令牌</h3><p class="muted">令牌只显示这一次，请立即复制并安全发送给该成员。</p><div id="newToken" class="token-box"></div><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:16px"><button class="btn secondary" onclick="copyToken()">复制令牌</button><button class="btn primary" onclick="closeTokenModal()">我已保存</button></div></div></div><div id="toast" class="toast hidden"></div>
<script>
let adminToken=sessionStorage.getItem('mcp_admin_token')||'';let currentPage='dashboard';const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opts={}){const res=await fetch('/admin/api'+path,{...opts,headers:{'Content-Type':'application/json','Authorization':'Bearer '+adminToken,...opts.headers}});const data=await res.json();if(res.status===401){logout();throw Error('管理密钥无效')}if(!res.ok)throw Error(data.error||'请求失败');return data}
async function login(){adminToken=$('adminToken').value.trim();try{await api('/overview');sessionStorage.setItem('mcp_admin_token',adminToken);$('login').classList.add('hidden');$('app').classList.remove('hidden');showPage('dashboard')}catch(e){$('loginError').textContent=e.message}}
function logout(){sessionStorage.removeItem('mcp_admin_token');adminToken='';$('app').classList.add('hidden');$('login').classList.remove('hidden')}
function showPage(page){currentPage=page;['dashboard','members','logs'].forEach(p=>{$(p+'Page').classList.toggle('hidden',p!==page);$('nav'+p[0].toUpperCase()+p.slice(1)).classList.toggle('active',p===page)});$('pageTitle').textContent={dashboard:'MCP 管理概览',members:'成员与权限',logs:'调用日志'}[page];refreshCurrent()}
function refreshCurrent(){if(currentPage==='dashboard')loadDashboard();if(currentPage==='members')loadMembers();if(currentPage==='logs')loadLogs()}
async function loadDashboard(){try{const o=(await api('/overview')).data;$('membersCount').textContent=o.members;$('enabledCount').textContent=o.enabled_members;$('callsCount').textContent=o.calls;$('failedCount').textContent=o.failed_calls;const l=(await api('/logs?page=1&page_size=8')).data;renderLogs(l,$('recentLogs'))}catch(e){toast(e.message)}}
async function loadMembers(){try{renderMembers((await api('/members')).data)}catch(e){toast(e.message)}}
function renderMembers(rows){if(!rows.length){$('membersTable').innerHTML='<div class="empty">暂无成员</div>';return}$('membersTable').innerHTML='<div class="table-wrap"><table><thead><tr><th>成员</th><th>令牌</th><th>问答</th><th>知识写入</th><th>状态</th><th>最近使用</th><th>操作</th></tr></thead><tbody>'+rows.map(m=>'<tr><td><b>'+esc(m.name)+'</b></td><td><code>'+esc(m.token_prefix)+'</code></td><td>'+perm(m.can_read)+'</td><td>'+perm(m.can_write)+'</td><td><span class="badge '+(m.enabled?'ok':'bad')+'">'+(m.enabled?'启用':'已禁用')+'</span></td><td>'+fmt(m.last_used_at)+'</td><td class="actions"><button class="btn secondary" onclick="toggleMember('+m.id+',\'can_read\','+!m.can_read+')">'+(m.can_read?'关闭问答':'开启问答')+'</button><button class="btn secondary" onclick="toggleMember('+m.id+',\'can_write\','+!m.can_write+')">'+(m.can_write?'关闭写入':'开启写入')+'</button><button class="btn '+(m.enabled?'danger':'primary')+'" onclick="toggleMember('+m.id+',\'enabled\','+!m.enabled+')">'+(m.enabled?'禁用':'启用')+'</button><button class="btn secondary" onclick="rotateToken('+m.id+')">换令牌</button></td></tr>').join('')+'</tbody></table></div>'}
const perm=v=>'<span class="badge '+(v?'ok':'')+'">'+(v?'允许':'禁止')+'</span>';async function toggleMember(id,key,value){try{await api('/members/'+id,{method:'PATCH',body:JSON.stringify({[key]:value})});loadMembers()}catch(e){toast(e.message)}}
function openMemberModal(){$('memberName').value='';$('canRead').checked=true;$('canWrite').checked=false;$('memberModal').classList.remove('hidden')}function closeMemberModal(){$('memberModal').classList.add('hidden')}
async function createMember(){try{const r=await api('/members',{method:'POST',body:JSON.stringify({name:$('memberName').value,can_read:$('canRead').checked,can_write:$('canWrite').checked})});closeMemberModal();showToken(r.token);loadMembers()}catch(e){toast(e.message)}}
async function rotateToken(id){if(!confirm('更换后旧令牌会立即失效，确定继续吗？'))return;try{const r=await api('/members/'+id+'/rotate-token',{method:'POST'});showToken(r.token);loadMembers()}catch(e){toast(e.message)}}
function showToken(v){$('newToken').textContent=v;$('tokenModal').classList.remove('hidden')}function closeTokenModal(){$('tokenModal').classList.add('hidden')}async function copyToken(){await navigator.clipboard.writeText($('newToken').textContent);toast('令牌已复制')}
async function loadLogs(){try{const q=new URLSearchParams({page:'1',page_size:'100'});if($('toolFilter').value)q.set('tool',$('toolFilter').value);if($('statusFilter').value)q.set('status',$('statusFilter').value);renderLogs((await api('/logs?'+q)).data,$('logsTable'))}catch(e){toast(e.message)}}
function renderLogs(rows,target){if(!rows.length){target.innerHTML='<div class="empty">暂无调用日志</div>';return}target.innerHTML='<div class="table-wrap"><table><thead><tr><th>时间</th><th>成员</th><th>工具</th><th>请求内容</th><th>知识库</th><th>状态</th><th>耗时</th><th>Request ID</th></tr></thead><tbody>'+rows.map(l=>'<tr title="'+esc(l.error_message)+'"><td>'+fmt(l.created_at)+'</td><td>'+esc(l.member_name||'未知')+'</td><td><code>'+esc(l.tool)+'</code></td><td style="max-width:330px;overflow:hidden;text-overflow:ellipsis">'+esc(l.subject||'-')+'</td><td><code>'+esc(l.knowledge_base_id||'-')+'</code></td><td><span class="badge '+(l.status==='success'?'ok':'bad')+'">'+esc(l.status)+'</span></td><td>'+l.duration_ms+' ms</td><td><code>'+esc(l.request_id||'-')+'</code></td></tr>').join('')+'</tbody></table></div>'}
function fmt(v){return v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'-'}function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2500)}
if(adminToken){$('login').classList.add('hidden');$('app').classList.remove('hidden');showPage('dashboard')}
</script></body></html>`
